const user = {
  email: "user@example.com",
  password: "123456",
  role: "amdin",
  name: "cc",
};

const cars = [
  {
    vin: "5TDKK3DC2CS220222",
    model: "Camry",
    year: 2019,
    make: "Toyota",
    price: 23500,
    door: 4,
    exteriorColor: "silver",
    interiorColor: "black",
    bodyStyle: "Sedan",
    fuelType: "gasoline",
    transmission: "automatic",
    driveType: "front-wheel drive",
    engineType: "inline-4",
    listPrice: 24000,
    mileage: 58000,
    displacement: 2.5,
  },
  {
    vin: "3GNKBBRA7KS635488",
    model: "CR-V",
    year: 2020,
    make: "Honda",
    price: 28900,
    door: 4,
    exteriorColor: "white",
    interiorColor: "beige",
    bodyStyle: "SUV",
    fuelType: "gasoline",
    transmission: "automatic",
    driveType: "all-wheel drive",
    engineType: "v6",
    listPrice: 30000,
    mileage: 158000,
    displacement: 1.5,
  },
  {
    vin: "5LMJJ2LT3JEL08464",
    model: "MKX",
    year: 2018,
    make: "Lincoln",
    price: 65200,
    door: 4,
    exteriorColor: "Black",
    interiorColor: "Brown",
    bodyStyle: "SUV",
    fuelType: "Gasoline",
    transmission: "Automatic",
    driveType: "All-wheel Drive",
    engineType: "V8",
    listPrice: 72000,
    mileage: 28000,
    displacement: 3.0,
  },
  {
    // id: 4,
    vin: "JTEBU5JR3G5342654",
    model: "Highlander",
    year: 2016,
    make: "Toyota",
    price: 24800,
    door: 4,
    exteriorColor: "Blue",
    interiorColor: "Gray",
    bodyStyle: "SUV",
    fuelType: "Gasoline",
    transmission: "Automatic",
    driveType: "All-wheel Drive",
    engineType: "V6",
    listPrice: 26000,
    mileage: 23000,
    displacement: 3.0,
  },
  {
    vin: "1C4PJMCB2FW539448",
    model: "Grand Cherokee",
    year: 2015,
    make: "Jeep",
    price: 21500,
    door: 4,
    exteriorColor: "Red",
    interiorColor: "Black",
    bodyStyle: "SUV",
    fuelType: "Gasoline",
    transmission: "Automatic",
    driveType: "All-wheel Drive",
    engineType: "V6",
    listPrice: 22000,
    mileage: 100000,
    displacement: 3.0,
  },
  {
    vin: "WBA7F2C54LWW17585",
    model: "7 Series",
    year: 2021,
    make: "BMW",
    price: 95000,
    door: 4,
    exteriorColor: "Gray",
    interiorColor: "White",
    bodyStyle: "Sedan",
    fuelType: "Gasoline",
    transmission: "Automatic",
    driveType: "Rear-wheel Drive",
    engineType: "V8",
    listPrice: 98000,
    mileage: 21000,
    displacement: 4.0,
  },
];

const images = [
  {  carId: 1, type: 'jpg', url: "null" },
  {  carId: 1, type: 'jpg',url: "null" },
  {  carId: 1,type: 'jpg', url: "null" },
  {  carId: 1, type: 'jpg',url: "null" },
  {  carId: 1, type: 'jpg',url: "null" },
  {  carId: 1, type: 'jpg',url: "null" },
  {  carId: 1, type: 'jpg',url: "null" },
  {  carId: 1,type: 'jpg', url: "null" },
  {  carId: 1,type: 'jpg',url: "null" },
  {  carId: 3, type: 'jpg',url: "null" },
  {  carId: 3, type: 'jpg',url: "null" },
  {  carId: 3, type: 'jpg',url: "null" },
  {  carId: 3, type: 'jpg',url: "null" },
  {  carId: 2, type: 'jpg',url: "null" },
  {  carId: 2, type: 'jpg',url: "null" },
  {  carId: 2, type: 'jpg',url: "null" },
  {  carId: 2,type: 'jpg', url: "null" },
  { carId: 2, type: 'jpg',url: "null" },
  { carId: 2, type: 'jpg',url: "null" },
];


const featureData = [
  // rewrite the featureData to be like that
  { id: 1, name: "4-Wheel Disc Brakes", category: "mechanicals" },
  { id: 2, name: "Power Steering", category: "mechanicals" },
  { id: 3, name: "Anti-Lock Brakes", category: "mechanicals" },
  { id: 4, name: "Push Button Start", category: "mechanicals" },
  { id: 5, name: "Driver Air Bag", category: "safety" },
  { id: 6, name: "Heated Mirrors", category: "safety" },
  { id: 7, name: "Passenger Air Bag", category: "safety" },
  { id: 8, name: "Rear Window Defrost", category: "safety" },
  { id: 9, name: "Side Air Bag", category: "safety" },
  { id: 10, name: "Traction Control", category: "safety" },
  { id: 11, name: "Alloy Wheels", category: "exterior" },
  { id: 12, name: "Aluminum Wheels", category: "exterior" },
  { id: 13, name: "Automatic Headlights", category: "exterior" },
  { id: 14, name: "Daytime Running Lights", category: "exterior" },
  { id: 15, name: "Fog Lights", category: "exterior" },
  { id: 16, name: "HID Headlights", category: "exterior" },
  { id: 17, name: "Luggage Rack", category: "exterior" },
  { id: 18, name: "Power Liftgate", category: "exterior" },
  { id: 19, name: "Air Conditioning", category: "interior" },
  { id: 20, name: "Anti-Theft System", category: "interior" },
  { id: 21, name: "Bucket Seats", category: "interior" },
  { id: 22, name: "Cruise Control", category: "interior" },
  { id: 23, name: "Keyless Entry", category: "interior" },
  { id: 24, name: "Power Door Locks", category: "interior" },
  { id: 25, name: "Security System", category: "interior" },
  { id: 26, name: "Tilt Steering Wheel", category: "interior" },
  { id: 27, name: "Power Mirrors", category: "powerOptions" },
  { id: 28, name: "Power Passenger Seat", category: "powerOptions" },
  { id: 29, name: "Power Seats", category: "powerOptions" },
  { id: 30, name: "Power Trunk", category: "powerOptions" },
  { id: 31, name: "AM/FM Radio", category: "media" },
  { id: 32, name: "Auxiliary Audio Input", category: "media" },
  { id: 33, name: "Bluetooth", category: "media" },
  { id: 34, name: "CD Player", category: "media" },
];


const carFeatures = [
  { carId: 1, featureId: 1 },
  { carId: 1, featureId: 2 },
  { carId: 1, featureId: 3 },
  { carId: 1, featureId: 4 },
  { carId: 2, featureId: 1 },
  { carId: 2, featureId: 2 },
  { carId: 2, featureId: 3 },
  { carId: 2, featureId: 4 },
  { carId: 3, featureId: 3 },
  { carId: 3, featureId: 2 },
  { carId: 4, featureId: 3 },
  { carId: 4, featureId: 2 },
  { carId: 5, featureId: 2 },
  { carId: 5, featureId: 3 },
  { carId: 5, featureId: 4 },
  { carId: 6, featureId: 2 },
  { carId: 6, featureId: 3 },
  { carId: 6, featureId: 4 },
  // create table data based on the safetyData and featureData, join them together on carID and featureID
  { carId: 1, featureId: 5 },
  { carId: 1, featureId: 6 },
  { carId: 1, featureId: 7 },
  { carId: 1, featureId: 8 },
  { carId: 1, featureId: 9 },
  { carId: 1, featureId: 10 },
  { carId: 2, featureId: 5 },
  { carId: 2, featureId: 6 },
  { carId: 2, featureId: 7 },
  { carId: 3, featureId: 6 },
  { carId: 3, featureId: 7 },
  { carId: 4, featureId: 5 },
  { carId: 4, featureId: 6 },
  { carId: 4, featureId: 7 },
  { carId: 4, featureId: 8 },
  { carId: 5, featureId: 5 },
  { carId: 5, featureId: 6 },
  { carId: 5, featureId: 7 },
  { carId: 5, featureId: 8 },
  { carId: 5, featureId: 9 },
  { carId: 5, featureId: 10 },
  { carId: 6, featureId: 7 },
  { carId: 6, featureId: 8 },
  { carId: 6, featureId: 9 },
  { carId: 6, featureId: 10 },
  // create table data based on the exteriorData and featureData, join them together on carID and featureID
  { carId: 1, featureId: 11 },
  { carId: 1, featureId: 12 },
  { carId: 1, featureId: 13 },
  { carId: 1, featureId: 14 },
  { carId: 1, featureId: 15 },
  { carId: 1, featureId: 16 },
  { carId: 1, featureId: 17 },
  { carId: 1, featureId: 18 },
  { carId: 2, featureId: 11 },
  { carId: 2, featureId: 12 },
  { carId: 2, featureId: 13 },
  { carId: 2, featureId: 14 },
  { carId: 2, featureId: 15 },
  { carId: 2, featureId: 16 },
  { carId: 2, featureId: 17 },
  { carId: 2, featureId: 18 },
  { carId: 3, featureId: 11 },
  { carId: 3, featureId: 12 },
  { carId: 3, featureId: 13 },
  { carId: 3, featureId: 14 },
  { carId: 3, featureId: 15 },
  { carId: 3, featureId: 16 },
  { carId: 3, featureId: 17 },
  { carId: 3, featureId: 18 },
  { carId: 4, featureId: 11 },
  { carId: 4, featureId: 12 },
  { carId: 4, featureId: 13 },
  { carId: 4, featureId: 14 },
  { carId: 4, featureId: 15 },
  { carId: 4, featureId: 16 },
  { carId: 4, featureId: 17 },
  { carId: 4, featureId: 18 },
  { carId: 5, featureId: 11 },
  { carId: 5, featureId: 12 },
  { carId: 5, featureId: 13 },
  { carId: 5, featureId: 14 },
  // create table data based on the InteriorData and featureData, join them together on carID and featureID
  { carId: 1, featureId: 19 },
  { carId: 1, featureId: 20 },
  { carId: 1, featureId: 21 },
  { carId: 1, featureId: 22 },
  { carId: 1, featureId: 23 },
  { carId: 1, featureId: 24 },
  { carId: 1, featureId: 25 },
  { carId: 1, featureId: 26 },
  { carId: 2, featureId: 21 },
  { carId: 2, featureId: 22 },
  { carId: 2, featureId: 23 },
  { carId: 2, featureId: 24 },
  { carId: 2, featureId: 25 },
  { carId: 3, featureId: 21 },
  { carId: 3, featureId: 22 },
  { carId: 3, featureId: 23 },
  { carId: 3, featureId: 24 },
  { carId: 3, featureId: 25 },
  { carId: 4, featureId: 21 },
  { carId: 4, featureId: 22 },
  { carId: 4, featureId: 23 },
  { carId: 4, featureId: 24 },
  { carId: 4, featureId: 25 },
  { carId: 5, featureId: 21 },
  { carId: 5, featureId: 22 },
  { carId: 5, featureId: 23 },
  { carId: 5, featureId: 24 },
  { carId: 5, featureId: 25 },
  { carId: 5, featureId: 19 },
  { carId: 5, featureId: 20 },
  { carId: 6, featureId: 21 },
  { carId: 6, featureId: 22 },
  { carId: 6, featureId: 23 },
  { carId: 6, featureId: 24 },
  { carId: 6, featureId: 25 },
  { carId: 6, featureId: 26 },
  { carId: 6, featureId: 19 },
  { carId: 6, featureId: 20 },
  // create table data based on the powerOptionsData and featureData, join them together on carID and featureID
  { carId: 1, featureId: 27 },
  { carId: 1, featureId: 28 },
  { carId: 1, featureId: 29 },
  { carId: 1, featureId: 30 },
  { carId: 2, featureId: 27 },
  { carId: 2, featureId: 28 },
  { carId: 2, featureId: 29 },
  { carId: 2, featureId: 30 },
  { carId: 3, featureId: 27 },
  { carId: 3, featureId: 28 },
  { carId: 3, featureId: 29 },
  { carId: 3, featureId: 30 },
  { carId: 4, featureId: 27 },
  { carId: 4, featureId: 28 },
  { carId: 4, featureId: 29 },
  { carId: 4, featureId: 30 },
  { carId: 5, featureId: 27 },
  { carId: 5, featureId: 28 },
  { carId: 5, featureId: 29 },
  { carId: 5, featureId: 30 },
  { carId: 6, featureId: 27 },
  { carId: 6, featureId: 28 },
  { carId: 6, featureId: 29 },
  { carId: 6, featureId: 30 },
  // create table data based on the MediaData and featureData, join them together on carID and featureID
  { carId: 1, featureId: 31 },
  { carId: 1, featureId: 32 },
  { carId: 1, featureId: 33 },
  { carId: 1, featureId: 34 },
  { carId: 2, featureId: 31 },
  { carId: 2, featureId: 32 },
  { carId: 2, featureId: 33 },
  { carId: 2, featureId: 34 },
  { carId: 3, featureId: 31 },
  { carId: 3, featureId: 32 },
  { carId: 3, featureId: 33 },
  { carId: 3, featureId: 34 },
  { carId: 4, featureId: 31 },
  { carId: 4, featureId: 32 },
  { carId: 4, featureId: 33 },
  { carId: 4, featureId: 34 },
  { carId: 5, featureId: 31 },
  { carId: 5, featureId: 32 },
  { carId: 5, featureId: 33 },
  { carId: 5, featureId: 34 },
  { carId: 6, featureId: 31 },
  { carId: 6, featureId: 32 },
  { carId: 6, featureId: 33 },
  { carId: 6, featureId: 34 },
];

module.exports = {
  user,
  cars,
  images,
  featureData,
  carFeatures,
};
