import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/globals.css"

import Header from "@/app/ui/main-header";
import Footer from "@/app/ui/main-footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Used Car",
  description: "Generated by ccc",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <div className=" flex flex-col">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
